/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cornucopia_patch_BSPatch */

#ifndef _Included_com_cornucopia_patch_BSPatch
#define _Included_com_cornucopia_patch_BSPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cornucopia_patch_BSPatch
 * Method:    mergePatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cornucopia_patch_BSPatch_mergePatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
