// Code generated by dagger-compiler.  Do not edit.
package com.cornucopia.di.dagger2;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class D2Module$$ModuleAdapter extends ModuleAdapter<D2Module> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public D2Module$$ModuleAdapter() {
    super(com.cornucopia.di.dagger2.D2Module.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public D2Module newModule() {
    return new com.cornucopia.di.dagger2.D2Module();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, D2Module module) {
    bindings.contributeProvidesBinding("com.cornucopia.di.dagger2.D2CollectionUtils", new ProvideStringUtilsProvidesAdapter(module));
  }

  /**
   * A {@code Binding<com.cornucopia.di.dagger2.D2CollectionUtils>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<com.cornucopia.di.dagger2.D2CollectionUtils>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideStringUtilsProvidesAdapter extends ProvidesBinding<D2CollectionUtils>
      implements Provider<D2CollectionUtils> {
    private final D2Module module;

    public ProvideStringUtilsProvidesAdapter(D2Module module) {
      super("com.cornucopia.di.dagger2.D2CollectionUtils", IS_SINGLETON, "com.cornucopia.di.dagger2.D2Module", "provideStringUtils");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<com.cornucopia.di.dagger2.D2CollectionUtils>}.
     */
    @Override
    public D2CollectionUtils get() {
      return module.provideStringUtils();
    }
  }
}
